<?php
/**
 * @file
 * comment_delete.install
 */

/**
 * Implements hook_install().
 */
function comment_delete_install() {
  db_update('system')
    ->fields(array('weight' => '1000'))
    ->condition('name', 'comment_delete', '=')
    ->execute();
}

/**
 * Implements hook_uninstall().
 */
function comment_delete_uninstall() {
  variable_del('comment_delete_default');
  variable_del('comment_delete_threshold');
}
